#ifndef COLLISION_TAGS_H
#define COLLISION_TAGS_H

#include <SDL3/SDL.h>

namespace Radix
{
	enum Colliders : unsigned int
	{
		ENEMY_COLLIDER_TAG,
		PLAYER_COLLIDER_TAG,
		HELIPORT_COLLIDER_TAG,
		ENEMY_BULLET_COLLIDER_TAG,
		PLAYER_BULLET_COLLIDER_TAG
	};

	enum Collisions : unsigned int
	{
		NO_COLLISION,
		PLAYER_ENEMY_COLLISION,
		PLAYER_HELIPORT_COLLISION,
		PLAYER_VEGETATION_COLLISION,
		PLAYER_ENEMY_BULLET_COLLISION,
		ENEMY_PLAYER_BULLET_COLLISION
	};
}

#endif