#ifndef COLLISION_TAGS_H
#define COLLISION_TAGS_H

#include <SDL3/SDL.h>

namespace Radix
{
	enum Colliders : unsigned int
	{
		PLAYER_COLLIDER,
		ENEMY_COLLIDER,
		ENEMY_PROJECTILE_COLLIDER,
		PLAYER_PROJECTILE_COLLIDER,
		LEVEL_COMPLETE_COLLIDER
	};

	enum Collisions : unsigned int
	{
		NO_COLLISION,
		PLAYER_ENEMY_COLLISION,
		PLAYER_PROJECTILE_COLLISION,
		ENEMY_PROJECTILE_COLLISION,
		PLAYER_VEGETATION_COLLISION,
		PLAYER_LEVEL_COMPLETE_COLLISION
	};
}

#endif