#ifndef TEXTURE_ID_H
#define TEXTURE_ID_H

enum TextureID : unsigned int
{
	TANK_TEXTURE_ID,
	RADAR_TEXTURE_ID,
	CHOPPER_TEXTURE_ID,
	HELIPORT_TEXTURE_ID,
	JUNGLE_MAP_TEXTURE_ID,
	ENEMY_BULLET_TEXTURE_ID
};

#endif
